### ISSUE TITLE
Instructions for Linux

### ISSUE THREAD

**Issue by arucard21** [Mik1ll/LuaRenamer#3]
I managed to follow the install instructions for Linux and added the file to the `.shoko/Shoko.CLI/plugins` folder. But since I am on Linux, I could not follow the usage instructions entirely. Instead, I modified `sample script.lua` manually and saved it as `my script.lua` in the same folder. At this point I'm not sure anymore what my next step should be.  Is `sample script.lua` the one that the renamer actually uses and should I not have created a new file? Or do I need to use a different name for it? Or add it to a configuration somewhere? I assume that Shoko Desktop does this for you, but I don't use that and it is not available on Linux. I'd appreciate some help with this. 

In case you're curious about how I modified the sample script without Shoko Desktop. I basically removed all the logic and only kept the variables for the different parts that go into the filename. This allowed me to run it in an online runtime ([JDoodle](https://www.jdoodle.com/execute-lua-online/)) so I could verify what the filename would be. This is the code that I used, maybe it'd be useful to add to the documentation somewhere (it could probably use better, more representative values for these variables).

```lua
local group = "[Fansub Group]"

local animename = "Isekai Anime"
animename = string.gsub(string.sub(animename, 0, 35), "%s+$", "") .. (#animename > 35 and "..." or "")

local episodename = "My First Day in Another World"
episodename = string.gsub(string.sub(episodename, 0, 35), "%s+$", "") .. (#episodename > 35 and "..." or "")

local episodenumber = "01"

local res = "1080p"
local codec = "AVC"
local bitdepth = "8bit"
local source = "HDD"

local fileinfo = "(" .. res .. " " .. codec .. " " .. bitdepth .. " " .. source .. ")"

local audiotag = "[AUDIOTAG]"
local subtag = "[SUBBED]"

local centag = "[UNCEN]"
local hashtag = "[deadbeef]"

local audios = "2.0"
local nametable = {group, animename, episodenumber, episodename, fileinfo, audiotag, subtag, centag, audios, hashtag}
filename = string.sub(table.concat(nametable, " "), 0, 120)

print(filename)
```

**Comment by Mik1ll** [comment]
Hey there, sorry about the trouble you're having regarding the renamer. I believe that this renamer is not currently functional on linux due to an issue with Shoko loading some plugin data, I forgot to remove the links on the previous releases. I have a potential fix in the works but haven't gotten around to testing it. I may be able to in the next few days.

To clear some of the confusion for future reference, the sample script.lua is not read from the plugin, but from Shoko's database. Currently the webui does not have an interface for renaming scripts, so options are [Desktop (apparently someone was able to get it working with wine)](https://github.com/ShokoAnime/ShokoDocs/blob/master/content/en/server/linux-desktop.md), http api, or editing the database directly. If you want to save via http api, the endpoint is POST http://localhost:8111/v1/RenameScript and body content: 
```
{
    "RenameScriptID": 1,
    "ScriptName": "Default",
    "Script": "<Script content, use a site like https://www.freeformatter.com/json-escape.html to escape newlines and quotes>",
    "IsEnabledOnImport": 1,
    "RenamerType": "LuaRenamer",
    "ExtraData": null
}
```

**Comment by arucard21** [comment]
Oh, the API call seems easy enough. Thanks for the detailed suggestion. Too bad it doesn't work in Linux. If you manage to get it fixed, that at least gives me some things to try. Is there a Shoko issue for getting the renamer working in Linux? Or is it an issue with the renamer? Could that issue maybe be linked here? Not sure how I'd know if and when it gets fixed otherwise.

**Comment by Mik1ll** [comment]
Okay from my testing it didn't seem to be a problem with shoko after all, it was the lua shared library that was incompatible with the glibc version in the docker image. I ended up needing to compile my own version of the library on the docker image.

I've updated the latest release with the new lua library, it seems to work for me. Let me know if you can get it working.
Done some testing with the api, and here is a way to preview renaming all files with your scripts (note this does not save your script so use the previous post for that): 
```
curl -s -o /dev/null -d '{"ScriptName":"AAA_WORKINGFILE_TEMP_AAA","Script":"<Script content, use a site like https://www.freeformatter.com/json-escape.html to escape newlines and quotes>","IsEnabledOnImport":0,"RenameScriptID":0,"RenamerType":"LuaRenamer","ExtraData":null}' -H 'Content-Type: application/json' 'http://localhost:8111/v1/RenameScript' && curl -s 'http://localhost:8111/v1/File/Rename/RandomPreview/2147483647/1' | jq '.[].VideoLocalID' | while read -r vlocal_id; do curl -s "http://localhost:8111/v1/File/Rename/Preview/$vlocal_id" | jq '.NewFileName'; done
```

**Comment by arucard21** [comment]
Oh wow, that was so fast. And those extra API calls are also really useful. Thank you so much! Is it correct that these API calls have no authentication? That's a bit concerning from a security perspective though that has nothing to do with you. Luckily, Shoko is only accessible from my own pc. I'll try it out and let you know how it goes

**Comment by arucard21** [comment]
I don't see a new release of LuaRenamer though. Where can I find the updated release that you mentioned? Or is it a new release of the Docker image? Though the latest daily is from 18 days ago. Does it just take a while to become available?

**Comment by Mik1ll** [comment]
> I don't see a new release of LuaRenamer though. Where can I find the updated release that you mentioned? Or is it a new release of the Docker image? Though the latest daily is from 18 days ago. Does it just take a while to become available?

Here: https://github.com/Mik1ll/LuaRenamer/releases/download/v0.2.0/LuaRenamer_0.2.0_Linux.tgz It's the same release but I reuploaded the Linux release. There weren't any code changes so didn't need to make a new release.

**Comment by arucard21** [comment]
Ah, that explains it. Thank you. I've used this now in Shoko but I haven't gotten it working yet. I'm using the "daily" Docker image, updated to the image currently on Docker Hub (from 2022-06-07). I hope this is the one for which your fix is supposed to work.

I've used those commands you showed to turn them into more convenient scripts. You can include those in your documentation for other Linux users (once this is working). 

`preview_rename_script.sh`
```shell
#!/usr/bin/env bash
if ! type jq > /dev/null
then
  echo "Please install jq to use this script"
fi
if [ $# -eq 0 ]
then 
	echo "Please provide the name of your Lua script as parameter to this script."
	echo "The script file should be made available in the same folder as this script."
	exit -1
fi
script_json="{
  \"ScriptName\": \"$1\",
  \"Script\": `jq -Rsa . "$1"`,
  \"IsEnabledOnImport\": 0,
  \"RenameScriptID\": 0,
  \"RenamerType\": \"LuaRenamer\",
  \"ExtraData\": null
}"
# Upload script to Shoko without enabling rename on import
curl -s -o /dev/null -d "$script_json" -H 'Content-Type: application/json' 'http://localhost:8111/v1/RenameScript'
# Get a random file to preview the effect of the renamer script
curl -s 'http://localhost:8111/v1/File/Rename/RandomPreview/1/1' | \
jq '.[].VideoLocalID' | \
while read -r vlocal_id
do
	curl -s "http://localhost:8111/v1/File/Rename/Preview/$vlocal_id" | jq '.NewFileName'
done
```
You should have your Lua script in the same folder. Assuming it's named `my_script.lua`, you can call this script like this:
`./preview_rename_script.sh "my_script.lua"`
I changed this from your example to only return a single file preview. That seemed easier to use for verifying the rename pattern. And since it uses a random file, you can always run it again to see how it works with a different file. 

The script for enabling the script is almost exactly the same.

`enable_rename_script.sh`
```shell
#!/usr/bin/env bash
if ! type jq > /dev/null
then
  echo "Please install jq to use this script"
fi
if [ $# -eq 0 ]
then 
	echo "Please provide the name of your Lua script as parameter to this script."
	echo "The script file should be made available in the same folder as this script."
	exit -1
fi
script_json="{
  \"ScriptName\": \"$1\",
  \"Script\": `jq -Rsa . "$1"`,
  \"IsEnabledOnImport\": 1,
  \"RenameScriptID\": 1,
  \"RenamerType\": \"LuaRenamer\",
  \"ExtraData\": null
}"
# Upload script to Shoko without enabling rename on import
curl -s -o /dev/null -d "$script_json" -H 'Content-Type: application/json' 'http://localhost:8111/v1/RenameScript'
```
As far as I could tell, only those 2 variables in the JSON were changed from 0 to 1. So that's the only difference with the preview script, aside from not getting any preview.

But like I said, it doesn't seem to work yet. With the preview script, it returns this:
`"ERROR: *Error: No script available for renamer"`
The Shoko log shows this exception:
> System.Exception: *Error: No script available for renamer at Shoko.Server.Renamer.LegacyRenamer.GetFilename(RenameEventArgs args) in /usr/src/app/source/Shoko.Server/Renamer/LegacyRenamer.cs:line 30 at Shoko.Server.Renamer.GroupAwareRenamer.GetFilename(RenameEventArgs args) in /usr/src/app/source/Shoko.Server/Renamer/GroupAwareSortingRenamer.cs:line 21 at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in /usr/src/app/source/Shoko.Server/Renamer/RenameFileHelper.cs:line 72 at Shoko.Server.ShokoServiceImplementation.RenameFilePreview(Int32 videoLocalID) in /usr/src/app/source/Shoko.Server/API/v1/Implementations/ShokoServiceImplementation/ShokoServiceImplementation_Utilities.cs:line 422

So it seems to still use the legacy renamer. I did see Shoko trying to load LuaRenamer in the log
> Trying to load /home/shoko/.shoko/Shoko.CLI/plugins/LuaRenamer/LuaRenamer.dll
> Trying to load /home/shoko/.shoko/Shoko.CLI/plugins/LuaRenamer/KeraLua.dll
> Trying to load /home/shoko/.shoko/Shoko.CLI/plugins/LuaRenamer/NLua.dll

I don't know if this means it was successfully loaded or not. I didn't see anything else about LuaRenamer in the log. Should it show something else in the logs when LuaRenamer is correctly loaded?

**Comment by Mik1ll** [comment]
The scriptName for RenameScriptID 0 probably needs to be "AAA_WORKINGFILE_TEMP_AAA" for preview to work, so only take the content not the file name there. I'll look into the exception if it still occurs after changing that. Permissions shouldn't affect the preview.

**Comment by arucard21** [comment]
Ah, I thought that the name was just a placeholder. It seems to work when I use that exact name. Though I'm now getting `ERROR: Sequence contains no matching element` as value for `NewFilename`. I thought that it might be a problem with my own script but I get the same when I run it with the sample script provided with the renamer.

This is the error that is logged:
> System.InvalidOperationException: Sequence contains no matching element at System.Linq.ThrowHelper.ThrowNoMatchException() at System.Linq.Enumerable.First[TSource](IEnumerable\`1 source, Func\`2 predicate) at LuaRenamer.LuaRenamer.CreateLuaEnv() at LuaRenamer.LuaRenamer.RunSandboxed(String code) at LuaRenamer.LuaRenamer.GetInfo() at LuaRenamer.LuaRenamer.GetFilename(RenameEventArgs args) at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in /usr/src/app/source/Shoko.Server/Renamer/RenameFileHelper.cs:line 72 at Shoko.Server.ShokoServiceImplementation.RenameFilePreview(Int32 videoLocalID) in /usr/src/app/source/Shoko.Server/API/v1/Implementations/ShokoServiceImplementation/ShokoServiceImplementation_Utilities.cs:line 422

I assume that `sample script.lua` should be a valid script so I'm not sure what's going wrong here. It does seem to be trying to use the script to show a preview of the renamed file. So I got further than I was before :smile:

**Comment by Mik1ll** [comment]
> Ah, I thought that the name was just a placeholder. It seems to work when I use that exact name. Though I'm now getting `ERROR: Sequence contains no matching element` as value for `NewFilename`. I thought that it might be a problem with my own script but I get the same when I run it with the sample script provided with the renamer.
> 
> This is the error that is logged:
> 
> > System.InvalidOperationException: Sequence contains no matching element at System.Linq.ThrowHelper.ThrowNoMatchException() at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate) at LuaRenamer.LuaRenamer.CreateLuaEnv() at LuaRenamer.LuaRenamer.RunSandboxed(String code) at LuaRenamer.LuaRenamer.GetInfo() at LuaRenamer.LuaRenamer.GetFilename(RenameEventArgs args) at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in /usr/src/app/source/Shoko.Server/Renamer/RenameFileHelper.cs:line 72 at Shoko.Server.ShokoServiceImplementation.RenameFilePreview(Int32 videoLocalID) in /usr/src/app/source/Shoko.Server/API/v1/Implementations/ShokoServiceImplementation/ShokoServiceImplementation_Utilities.cs:line 422
> 
> I assume that `sample script.lua` should be a valid script so I'm not sure what's going wrong here. It does seem to be trying to use the script to show a preview of the renamed file. So I got further than I was before 😄

From that error it seems that some data I assumed would have to be there is missing for the file it tried to process, could you try with other files and tell me about the file if the others worked. By the way, if you still have the print function at the end of the script remove that because it's not defined in the environment.

**Comment by arucard21** [comment]
I have tried to get the preview with a random file several times. I even ran it to try 1000 different files at random (changing the max size in the API call that retrieves the list of random files). Almost all of them give this same error, a few returned `"ERROR: No anime and/or episode info"` which probably just means it was an unrecognized file. I used the provided `sample script.lua` for this, without any modifications. 

As for the print function in the script I showed earlier, that is not the script I'm using here. That script was just intended to preview the renaming in an external Lua runtime, like JDoodle that I linked to. The print function was then necessary to show what the filename variable became. Of course, this is not necessary anymore, given that we can a preview of the rename from Shoko itself through these API calls.

But since you said that it did work for you, I tried it myself with the rename script after removing the print line. Surprisingly, this returned the same `"ERROR: Sequence contains no matching element"` message. Since this script used placeholder values for all the variables that are used, and doesn't try to get anything from Shoko, I expected it to just rename everything to the filename according to these placeholder values. Since it gave the same error, it seems unlikely that this problem is caused by the script trying to retrieve data that isn't available in Shoko. But then I don't know what sequence it was trying to match, that caused this error.

**Comment by Mik1ll** [comment]
Seems like nothing to do with the script, could you give me the result of `curl -s 'http://localhost:8111/v1/File/Rename/RandomPreview/1/1'`, There might be something I can figure out from that.

**Comment by arucard21** [comment]
I tried looking into the code for a bit and I noticed that the stacktrace that I showed earlier is not the same as the most recent one I'm getting. The important difference is that it is showing that the problem is on line 449 and not on 422. This is the latest stacktrace that I got for the error.
> System.InvalidOperationException: Sequence contains no matching element
    at System.Linq.ThrowHelper.ThrowNoMatchException()
    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
    at LuaRenamer.LuaRenamer.CreateLuaEnv()
    at LuaRenamer.LuaRenamer.RunSandboxed(String code)
    at LuaRenamer.LuaRenamer.GetInfo()
    at LuaRenamer.LuaRenamer.GetFilename(RenameEventArgs args)
    at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in /usr/src/app/source/Shoko.Server/Renamer/RenameFileHelper.cs:line 72
     at Shoko.Server.ShokoServiceImplementation.RenameFilePreview(Int32 videoLocalID) in /usr/src/app/source/Shoko.Server/API/v1/Implementations/ShokoServiceImplementation/ShokoServiceImplementation_Utilities.cs:line 449

So it is showing that the problem originates on this line:
https://github.com/ShokoAnime/ShokoServer/blob/master/Shoko.Server/API/v1/Implementations/ShokoServiceImplementation/ShokoServiceImplementation_Utilities.cs#L449
But that is the end of the `RenameFilePreview` function, not where `GetFilename` should be called, as indicated in the stacktrace. That line should be 422, as it was in the earlier stacktrace that I showed. I think the difference is that I updated the Docker image that I used so it uses the current image available with the daily tag. It seems that the code in that image is not exactly the same as what is on the master branch in git. I couldn't find any previous code changes to this file that caused the `GetFilename` line to end up on line 449. So perhaps this is using a different branch, or local code changes. Maybe that is why `LuaRenamer` is not getting what it expects.

**Comment by arucard21** [comment]
As requested. I piped it through `jq` to make it more readable.
`$ curl -s 'http://localhost:8111/v1/File/Rename/RandomPreview/1/1' | jq
`
```json
[
  {
    "IsWatched": 0,
    "WatchedDate": null,
    "ResumePosition": 0,
    "Places": [
      {
        "ImportFolder": {
          "IsWatched": 1,
          "IsDropSource": 0,
          "IsDropDestination": 0,
          "ImportFolderLocation": "/mnt/anime/",
          "ImportFolderID": 1,
          "ImportFolderType": 1,
          "ImportFolderName": "Anime"
        },
        "VideoLocal_Place_ID": 10620,
        "VideoLocalID": 10620,
        "FilePath": "Naruto Shippuuden/Naruto Shippuuden - 047 - Sneak In! Den of the Poisonous Snake .mkv",
        "ImportFolderID": 1,
        "ImportFolderType": 1
      }
    ],
    "Media": {
      "Parts": [
        {
          "Accessible": 0,
          "Exists": 0,
          "Streams": [
            {
              "Duration": 1389296,
              "Height": 480,
              "Width": 624,
              "SubIndex": 0,
              "Id": 1,
              "ScanType": "progressive",
              "RefFrames": 6,
              "Profile": "main",
              "HeaderStripping": 1,
              "FrameRateMode": "cfr",
              "FrameRate": 29.97,
              "ColorSpace": "yuv",
              "CodecID": "V_MPEG4/ISO/AVC",
              "ChromaSubsampling": "4:2:0",
              "Cabac": 1,
              "BitDepth": 8,
              "Index": 1,
              "Codec": "H264",
              "StreamType": 1,
              "Channels": 0,
              "Selected": 0,
              "Default": 1,
              "Forced": 0,
              "PixelAspectRatio": "619:624"
            },
            {
              "Language": "Japanese",
              "Duration": 1389000,
              "Height": 0,
              "SubIndex": 0,
              "Id": 2,
              "CodecID": "A_AAC-2",
              "Index": 2,
              "Codec": "A_AAC-2",
              "StreamType": 2,
              "SamplingRate": 44100,
              "LanguageCode": "jpn",
              "Channels": 2,
              "Selected": 0,
              "DialogNorm": "0",
              "Default": 1,
              "Forced": 0
            },
            {
              "Language": "English",
              "Duration": 0,
              "Height": 0,
              "SubIndex": 0,
              "Id": 3,
              "CodecID": "S_TEXT/ASS",
              "Index": 3,
              "Codec": "ASS",
              "StreamType": 3,
              "LanguageCode": "eng",
              "Channels": 0,
              "Selected": 0,
              "Format": "ASS",
              "Default": 1,
              "Forced": 0
            }
          ],
          "Size": 0,
          "Duration": 0,
          "Id": 0
        }
      ],
      "Duration": 1389000,
      "VideoFrameRate": "NTSC",
      "Container": "mkv",
      "VideoCodec": "V_MPEG4/ISO/AVC",
      "AudioCodec": "A_AAC-2",
      "AudioChannels": 2,
      "AspectRatio": 1.3,
      "Height": 480,
      "Width": 624,
      "Bitrate": 658139,
      "Id": 10620,
      "VideoResolution": "480p",
      "OptimizedForStreaming": 1
    },
    "Duration": 1389,
    "VideoLocalID": 10620,
    "Hash": "39AC27B09037734A0E27962744658ED9",
    "CRC32": "1C8040A5",
    "MD5": "68AF3346F25101B46D12C7181A8EA484",
    "SHA1": "D931C966C0365D0CE59B3CB2EEAB93C865139721",
    "HashSource": 1,
    "FileSize": 114293792,
    "IsIgnored": 0,
    "DateTimeUpdated": "2021-08-20T04:01:42.2604738",
    "DateTimeCreated": "0001-01-01T00:00:00",
    "IsVariation": 0,
    "FileName": "Naruto Shippuuden - 047 - Sneak In! Den of the Poisonous Snake .mkv"
  }
]
```

**Comment by Mik1ll** [comment]
Okay I see this issue, I made an assumption that the user would have at least one import folder set as a Drop Destination. I'll make a code fix, but you can just set the folder you are keeping the files in to a drop destination.

**Comment by arucard21** [comment]
Ah, that assumption makes sense for when you have it configured to actually rename your files. Since I didn't use it like that yet, I didn't have a drop destination defined. But you're correct, after changing the import folder to a drop destination, it works beautifully :smile: Thank you so much for helping with this. 

I did know that the problem was something to do with creating the Lua environment (or something in the top section of the stacktrace). I just thought that the line difference might be an indication of using a different code base than I was expecting. But I'm also not familiar with Lua so perhaps it's like you said, something like a change during compiling. But that doesn't matter anymore since it works now. 

I think it might be useful to add some of these findings to the documentation though. For the next poor soul trying to use this on Linux :sunglasses:

**Comment by Mik1ll** [comment]
Good to hear, I think I'll add the shell scripts to the Linux archive and a section in the readme. Leaving this issue open until I do that. You can hit me up on Discord Mikill#5239 if you need any help with creating a script or other questions.

**Comment by arucard21** [comment]
Thanks! I don't really go on Discord so I'll probably ask here again :smile:  Hope you don't mind. It also keeps the information visible to others that may run into the same problem. 

Changing the script seems doable now that I can get a preview. The only question I have is fairly minor in comparison to the problem we discussed here (and completely unrelated). But since you mentioned it, I'll ask anyway.

The renamer currently changes all special characters to underscore. And that seems to be outside of the script that I provide. But I actually wanted it to just remove the special character (instead of replacing it with an underscore). Is there any way to do that? Since it's entirely unrelated, I can also just create a separate issue for it.

**Comment by Mik1ll** [comment]
You can set remove_illegal_chars or replace_illegal_chars to true. First removes them entirely and second will replace the invalid chars with [unicode alternatives](https://github.com/Mik1ll/LuaRenamer/blob/4ab331db2560e71efe51f2722f13e7e28b74415e/LuaRenamer/Utils.cs#L19).
I don't mind if you use github issues either.

**Comment by arucard21** [comment]
Oh, that worked quite well. I forgot about the `defs.lua` file. It seems like i can get it to work just the way I want now. Thank you so much!
