### ISSUE TITLE
Error when renaming files

### ISSUE THREAD

**Issue by moxz** [Mik1ll/LuaRenamer#58]
Sorry I don't know exactly what to provide for information but i am trying to rename some files.
I get this error on some files but not on others.
*Error: File: /_/LuaRenamer/LuaContext.cs Method: <MediaInfoToDict>b__31_1 Line: 413 | Object reference not set to an instance of an object.

Shokoserver 5.0.0 in Docker : Latest  (Linux)
LuaRenamer_Docker_AMD64_v5.2.2-0-gc437bac.zip

Example filename that does not work:
[CBM]Code Geass - Hangyaku no Lelouch - 25 - Zero (1920x1080 10bit) [b17cb2bf].mkv

Example filename that works:
[CBM]Code Geass - Hangyaku no Lelouch - S04 - Picture Drama 1 (1920x1080 10bit) [ba7732f5].mkv

I don't see any difference in the filenames that should cause the first one not to work while the second one does work.

**Comment by Mik1ll** [comment]
Should be fixed with https://github.com/Mik1ll/LuaRenamer/releases/tag/v5.2.3

Thanks for the report
