### ISSUE TITLE
Unable to get audio codec

### ISSUE THREAD

**Issue by pokyunn** [Mik1ll/LuaRenamer#70]
Hi I'm not sure if its a problem in this plugin, or if Shoko is not passing audio info to it.

But `file.media.audio.codec` is always empty, in my test files it should contain AAC as sonarr/radar/tdarr cand find using mediainfo.

**Comment by Mik1ll** [comment]
Since a file can have 0 or more audio tracks, file.media.audio is an array, you can access it using something like this:
`local audiocodec = #file.media.audio > 1 and file.media.audio[1].codec or ""`
or
`local audiocodecs = table.concat(from(file.media.audio):select("codec"):toArray(), ", ")`

**Comment by pokyunn** [comment]
Thanks, it worked, my error was taking index 0 from array, as i only collect animes with Japanese audio tracks fixing [1] wont be a problem.

I ended up with this naming, this way I have all i need in files, and force Emby to display like shoko+shokofin+jellyfin (but image quility is worst and need some manual match using the anidb id

```
media/
├── movies
│   └── Accel World： Infinite Burst (2016) [anidb-11680]
│       └── Accel World： Infinite Burst [BluRay 1080p] [HEVC 10bit] [AAC 2.0] [ANSK].mkv
└── series
    ├── Accel World OVA [anidb-9187]
    │   └── Accel World OVA - S1E001 - Reverberation [BluRay 720p] [H264 10bit] [AAC 2.0] [ANSK].mkv
    └── Accel World [anidb-8691]
        └── Accel World - S1E001 - Acceleration [BluRay 720p] [H264 10bit] [AAC 2.0] [ANSK].mkv
```
Accel world was good for testing as it have all 3 types I wanted to display separated
